// ---------------------------------------------------------------------------
// GTA 6 News Hub — content data source (ADR-003)
// Swapping to a live CMS/JSON API later only means replacing getArticles().
// ---------------------------------------------------------------------------

// Worldwide channels the hub aggregates (ADR-007: multi-channel, worldwide).
export const CHANNELS = [
  { id: 'rockstar',  name: 'Rockstar Games (Official)', type: 'Official',   region: 'Global', lang: 'EN', url: 'https://www.rockstargames.com/VI', desc: 'Official site, newswire & press releases.' },
  { id: 'youtube',   name: 'Rockstar on YouTube',       type: 'Video',      region: 'Global', lang: 'EN', url: 'https://www.youtube.com/@RockstarGames', desc: 'Official trailers & reveals.' },
  { id: 'reddit',    name: 'r/GTA6',                     type: 'Community',  region: 'Global', lang: 'EN', url: 'https://www.reddit.com/r/GTA6/', desc: 'Largest GTA 6 discussion community.' },
  { id: 'x',         name: 'X / Twitter (#GTA6)',        type: 'Social',     region: 'Global', lang: 'Multi', url: 'https://twitter.com/search?q=%23GTA6', desc: 'Real-time chatter & breaking posts.' },
  { id: 'ign',       name: 'IGN',                        type: 'Press',      region: 'US',     lang: 'EN', url: 'https://www.ign.com/games/grand-theft-auto-6', desc: 'Coverage, previews & interviews.' },
  { id: 'gamespot',  name: 'GameSpot',                   type: 'Press',      region: 'US',     lang: 'EN', url: 'https://www.gamespot.com/games/grand-theft-auto-6/', desc: 'News & analysis.' },
  { id: 'eurogamer', name: 'Eurogamer',                  type: 'Press',      region: 'EU',     lang: 'EN', url: 'https://www.eurogamer.net/', desc: 'European gaming coverage.' },
  { id: 'gamestar',  name: 'GameStar',                   type: 'Press',      region: 'DE',     lang: 'DE', url: 'https://www.gamestar.de/', desc: 'German-language coverage.' },
  { id: 'jeuxvideo', name: 'Jeuxvideo.com',              type: 'Press',      region: 'FR',     lang: 'FR', url: 'https://www.jeuxvideo.com/', desc: 'French-language coverage.' },
  { id: 'famitsu',   name: 'Famitsu',                    type: 'Press',      region: 'JP',     lang: 'JP', url: 'https://www.famitsu.com/', desc: 'Japanese gaming press.' },
  { id: 'wiki',      name: 'GTA Fandom Wiki',            type: 'Reference',  region: 'Global', lang: 'Multi', url: 'https://gta.fandom.com/wiki/Grand_Theft_Auto_VI', desc: 'Community encyclopedia.' },
  { id: 'leaks',     name: 'Leak Watch (community)',     type: 'Leaks',      region: 'Global', lang: 'EN', url: 'https://www.reddit.com/r/GTA6/', desc: 'Unverified rumors — treat with caution.' },
];

const DAY = 86400000;
// Relative dates are derived from a fixed "now" so the demo stays stable.
const NOW = new Date('2026-06-27T12:00:00Z').getTime();
const ago = (d) => new Date(NOW - d * DAY).toISOString();

export const ARTICLES = [
  {
    id: 'a1',
    title: 'GTA 6 confirmed for November 19, 2026 — Rockstar locks the date',
    excerpt: 'Rockstar Games confirms the worldwide release date for Grand Theft Auto VI on PS5 and Xbox Series X|S.',
    body: `Rockstar Games has officially confirmed that Grand Theft Auto VI will launch on November 19, 2026 for PlayStation 5 and Xbox Series X|S. The announcement ends months of speculation about a possible delay.\n\nThe studio reiterated that the game is set in the state of Leonida and its sprawling city of Vice City, returning the series to a modern-day Florida-inspired setting. A PC version was not dated at this time, consistent with Rockstar's past staggered rollouts.\n\nPre-orders are expected to open closer to launch. Rockstar thanked fans for their patience and promised additional media "in the months ahead."`,
    category: 'Official',
    source: 'rockstar', sourceUrl: 'https://www.rockstargames.com/VI',
    region: 'Global', lang: 'EN',
    author: 'Newswire',
    date: ago(2),
    image: 'gradient-1',
    verified: true,
    likes: 4821,
    featured: true,
  },
  {
    id: 'a2',
    title: 'Trailer 2 breaks views record in first 24 hours',
    excerpt: 'The second official trailer racked up record-breaking numbers across YouTube within a single day.',
    body: `The second official trailer for GTA 6 has shattered first-day view records, amassing tens of millions of views within 24 hours of release. Fans dissected every frame for clues about the map, the dual protagonists Lucia and Jason, and returning series staples.\n\nAnalysts noted the trailer's heavy emphasis on a living, reactive world — dynamic NPC routines, weather, and a notably denser Vice City skyline.`,
    category: 'Trailer',
    source: 'youtube', sourceUrl: 'https://www.youtube.com/@RockstarGames',
    region: 'Global', lang: 'EN',
    author: 'Media Desk',
    date: ago(5),
    image: 'gradient-2',
    verified: true,
    likes: 9210,
    featured: false,
  },
  {
    id: 'a3',
    title: 'Map size reportedly the largest in series history',
    excerpt: 'Community analysis of trailer footage suggests Leonida dwarfs previous GTA maps.',
    body: `Community cartographers piecing together trailer footage believe the state of Leonida will be the largest open world Rockstar has ever shipped, combining a dense Vice City with extensive rural wetlands, beaches and the Keys-inspired island chain.\n\nNothing here is official — treat reconstructed maps as fan estimates until Rockstar confirms dimensions.`,
    category: 'Map',
    source: 'reddit', sourceUrl: 'https://www.reddit.com/r/GTA6/',
    region: 'Global', lang: 'EN',
    author: 'r/GTA6',
    date: ago(8),
    image: 'gradient-3',
    verified: false,
    likes: 3344,
    featured: false,
  },
  {
    id: 'a4',
    title: 'Who are Lucia and Jason? A look at GTA 6\'s dual protagonists',
    excerpt: 'For the first time, a mainline GTA features a playable female lead alongside her partner.',
    body: `GTA 6 marks a series first with Lucia, a playable female protagonist, partnered with Jason in a Bonnie-and-Clyde-style story. Rockstar has shown the pair navigating heists and a relationship under pressure.\n\nExpect a narrative built around switching between the two, echoing the multi-protagonist structure pioneered in GTA V but tightened around a central duo.`,
    category: 'Characters',
    source: 'ign', sourceUrl: 'https://www.ign.com/games/grand-theft-auto-6',
    region: 'US', lang: 'EN',
    author: 'IGN Staff',
    date: ago(11),
    image: 'gradient-4',
    verified: true,
    likes: 5102,
    featured: false,
  },
  {
    id: 'a5',
    title: 'PC version: what we know (and don\'t)',
    excerpt: 'No PC date yet — here is how Rockstar has handled PC launches historically.',
    body: `As with GTA V and RDR2, GTA 6 launches first on current-gen consoles, with PC traditionally following months later. Rockstar has not announced a PC date.\n\nIf history repeats, PC players may wait the better part of a year — though Rockstar has faced growing pressure to shorten that gap.`,
    category: 'Official',
    source: 'gamespot', sourceUrl: 'https://www.gamespot.com/games/grand-theft-auto-6/',
    region: 'US', lang: 'EN',
    author: 'GameSpot',
    date: ago(14),
    image: 'gradient-5',
    verified: true,
    likes: 2210,
    featured: false,
  },
  {
    id: 'a6',
    title: 'Leak roundup: separating signal from noise',
    excerpt: 'A measured look at the week\'s rumors and why most should be taken with caution.',
    body: `Another week, another wave of GTA 6 "leaks." We compiled the most-discussed claims and rated their plausibility. As always: unverified community leaks are not confirmation. Rockstar rarely comments on rumors.\n\nOur credibility meter below lets the community vote on how believable each rumor is.`,
    category: 'Leak',
    source: 'leaks', sourceUrl: 'https://www.reddit.com/r/GTA6/',
    region: 'Global', lang: 'EN',
    author: 'Leak Watch',
    date: ago(17),
    image: 'gradient-6',
    verified: false,
    likes: 1880,
    featured: false,
  },
  {
    id: 'a7',
    title: 'GTA 6 in Deutschland: Was Fans hier wissen müssen',
    excerpt: 'Deutschsprachige Zusammenfassung der wichtigsten offiziellen Ankündigungen.',
    body: `Die deutschsprachige Community fiebert dem Release am 19. November 2026 entgegen. GameStar und andere Magazine fassen die offiziellen Ankündigungen zusammen: Schauplatz ist der Bundesstaat Leonida mit Vice City.\n\nEine USK-Einstufung steht noch aus, wird aber wie bei früheren Teilen erwartet.`,
    category: 'Official',
    source: 'gamestar', sourceUrl: 'https://www.gamestar.de/',
    region: 'DE', lang: 'DE',
    author: 'GameStar',
    date: ago(20),
    image: 'gradient-7',
    verified: true,
    likes: 1290,
    featured: false,
  },
  {
    id: 'a8',
    title: 'Vice City returns: a modern take on the 1986 classic',
    excerpt: 'How Rockstar is reimagining its most iconic city for current-gen hardware.',
    body: `Vice City, last visited in the 1980s-set classic, returns in a contemporary form. Trailer footage shows neon-soaked nightlife, beachfront high-rises and a denser, more reactive crowd than any prior GTA.\n\nThe city is the beating heart of the new state of Leonida.`,
    category: 'Map',
    source: 'eurogamer', sourceUrl: 'https://www.eurogamer.net/',
    region: 'EU', lang: 'EN',
    author: 'Eurogamer',
    date: ago(24),
    image: 'gradient-8',
    verified: true,
    likes: 2670,
    featured: false,
  },
  {
    id: 'a9',
    title: 'Pre-order details expected later this year',
    excerpt: 'Rockstar signals pre-orders and editions will be announced closer to launch.',
    body: `Rockstar has indicated that pre-order details, special editions and platform-specific bonuses will arrive closer to the November 2026 launch. No pricing has been confirmed.\n\nWe'll update this section the moment official storefront listings go live.`,
    category: 'Official',
    source: 'rockstar', sourceUrl: 'https://www.rockstargames.com/VI',
    region: 'Global', lang: 'EN',
    author: 'Newswire',
    date: ago(28),
    image: 'gradient-9',
    verified: true,
    likes: 1450,
    featured: false,
  },
  {
    id: 'a10',
    title: 'Soundtrack speculation: which radio stations could return?',
    excerpt: 'Fans hope for a sprawling licensed soundtrack worthy of a modern Vice City.',
    body: `GTA radio is a series institution. With a 1980s-rooted Vice City reborn in the present day, fans are speculating about genre-spanning stations blending synthwave nostalgia with contemporary Latin, hip-hop and pop.\n\nNothing is confirmed — but Rockstar's music licensing has historically been a highlight.`,
    category: 'Trailer',
    source: 'reddit', sourceUrl: 'https://www.reddit.com/r/GTA6/',
    region: 'Global', lang: 'EN',
    author: 'r/GTA6',
    date: ago(33),
    image: 'gradient-10',
    verified: false,
    likes: 990,
    featured: false,
  },
  {
    id: 'a11',
    title: 'Famitsu: 日本でのGTA 6への期待',
    excerpt: 'Japanese press weighs in on expectations for the worldwide launch.',
    body: `Japanese outlet Famitsu covers growing anticipation for GTA 6 ahead of its worldwide November 2026 release. Coverage focuses on the dual-protagonist structure and the scope of the new open world.\n\nLocalization details for the Japanese market have not yet been announced.`,
    category: 'Official',
    source: 'famitsu', sourceUrl: 'https://www.famitsu.com/',
    region: 'JP', lang: 'JP',
    author: 'Famitsu',
    date: ago(38),
    image: 'gradient-11',
    verified: true,
    likes: 760,
    featured: false,
  },
  {
    id: 'a12',
    title: 'Online mode: what could the future of GTA Online look like?',
    excerpt: 'With GTA V\'s online juggernaut, all eyes are on GTA 6\'s multiplayer plans.',
    body: `GTA Online generated enormous revenue across a decade. Rockstar has not detailed GTA 6's online component, but expectations are high for a next-generation evolution rather than a simple sequel.\n\nExpect more details after the single-player launch, mirroring GTA V's rollout.`,
    category: 'Official',
    source: 'ign', sourceUrl: 'https://www.ign.com/games/grand-theft-auto-6',
    region: 'US', lang: 'EN',
    author: 'IGN Staff',
    date: ago(45),
    image: 'gradient-12',
    verified: false,
    likes: 1670,
    featured: false,
  },
];

export const TIMELINE = [
  { date: '2022-02-04', title: 'Rockstar confirms development', desc: 'Rockstar officially confirms the next Grand Theft Auto is in active development.' },
  { date: '2023-12-04', title: 'First trailer revealed', desc: 'Trailer 1 debuts, confirming Vice City, the state of Leonida, and protagonist Lucia.' },
  { date: '2025-05-02', title: 'Window narrows to 2026', desc: 'Rockstar narrows the release window, building anticipation.' },
  { date: '2026-06-22', title: 'Trailer 2 drops', desc: 'A second trailer breaks first-day view records.' },
  { date: '2026-11-19', title: 'Worldwide release', desc: 'GTA 6 launches on PS5 and Xbox Series X|S.' },
];

export const FAQ = [
  { q: 'When does GTA 6 release?', a: 'November 19, 2026 on PlayStation 5 and Xbox Series X|S.' },
  { q: 'Is there a PC version?', a: 'Not dated yet. Rockstar has historically released PC versions after consoles.' },
  { q: 'Where is GTA 6 set?', a: 'In the state of Leonida, centered on a modern reimagining of Vice City.' },
  { q: 'Who are the protagonists?', a: 'Lucia — the series\' first playable female lead — and her partner Jason.' },
  { q: 'How do I tell verified news from rumors?', a: 'Look for the "Verified" badge. Items marked "Rumor" come from unofficial channels.' },
  { q: 'Are leaks reliable?', a: 'Treat all leaks with caution. Only Rockstar announcements are confirmation.' },
];

export const POLLS = [
  { id: 'p1', q: 'Which feature are you most excited about?', options: ['Dual protagonists', 'Bigger map', 'Improved GTA Online', 'Modern Vice City'] },
  { id: 'p2', q: 'Will the PC version arrive within 6 months of launch?', options: ['Yes', 'No', 'No idea'] },
];

export const CHARACTERS = [
  { name: 'Lucia', role: 'Protagonist', desc: 'The series\' first playable female lead.', image: 'gradient-2' },
  { name: 'Jason', role: 'Protagonist', desc: 'Lucia\'s partner in a Bonnie-and-Clyde story.', image: 'gradient-4' },
  { name: 'Vice City', role: 'Setting', desc: 'A modern reimagining of the iconic city.', image: 'gradient-8' },
  { name: 'Leonida', role: 'State', desc: 'The largest open world in series history (reported).', image: 'gradient-3' },
];

export function getArticles() {
  return ARTICLES.slice();
}
