// ---------------------------------------------------------------------------
// GTA 6 News Hub — content data source (ADR-003)
// Swapping to a live CMS/JSON API later only means replacing getArticles().
// ---------------------------------------------------------------------------

// Worldwide channels the hub aggregates (ADR-007: multi-channel, worldwide).
export const CHANNELS = [
  { id: 'rockstar',        name: 'Rockstar Games (Official)',  type: 'Official',   region: 'Global', lang: 'EN',    url: 'https://www.rockstargames.com/VI', desc: 'Official site, newswire & press releases.' },
  { id: 'youtube',        name: 'Rockstar on YouTube',        type: 'Video',      region: 'Global', lang: 'EN',    url: 'https://www.youtube.com/@RockstarGames', desc: 'Official trailers & reveals.' },
  { id: 'instagram',      name: 'Rockstar on Instagram',      type: 'Social',     region: 'Global', lang: 'EN',    url: 'https://www.instagram.com/rockstargames/', desc: 'Visual updates & behind-the-scenes teasers.' },
  { id: 'tiktok',         name: 'TikTok #GTA6',               type: 'Social',     region: 'Global', lang: 'Multi', url: 'https://www.tiktok.com/tag/gta6', desc: 'Short-form fan videos, leaks and reaction content.' },
  { id: 'gtaseriesvideos',name: 'GTASeriesVideos (YouTube)',  type: 'Video',      region: 'Global', lang: 'EN',    url: 'https://www.youtube.com/@GTASeriesVideos', desc: 'Top fan-run channel: breakdowns, analysis & news.' },
  { id: 'reddit',         name: 'r/GTA6',                     type: 'Community',  region: 'Global', lang: 'EN',    url: 'https://www.reddit.com/r/GTA6/', desc: 'Largest GTA 6 discussion community.' },
  { id: 'discord',        name: 'GTA 6 Community Discord',    type: 'Community',  region: 'Global', lang: 'Multi', url: 'https://discord.gg/gta', desc: 'Real-time chat, speculation and event announcements.' },
  { id: 'x',              name: 'X / Twitter (#GTA6)',        type: 'Social',     region: 'Global', lang: 'Multi', url: 'https://twitter.com/search?q=%23GTA6', desc: 'Real-time chatter & breaking posts.' },
  { id: 'ign',            name: 'IGN',                        type: 'Press',      region: 'US',     lang: 'EN',    url: 'https://www.ign.com/games/grand-theft-auto-6', desc: 'Coverage, previews & interviews.' },
  { id: 'gamespot',       name: 'GameSpot',                   type: 'Press',      region: 'US',     lang: 'EN',    url: 'https://www.gamespot.com/games/grand-theft-auto-6/', desc: 'News & analysis.' },
  { id: 'eurogamer',      name: 'Eurogamer',                  type: 'Press',      region: 'EU',     lang: 'EN',    url: 'https://www.eurogamer.net/', desc: 'European gaming coverage.' },
  { id: 'gamestar',       name: 'GameStar',                   type: 'Press',      region: 'DE',     lang: 'DE',    url: 'https://www.gamestar.de/', desc: 'German-language coverage.' },
  { id: 'pcgames',        name: 'PC Games',                   type: 'Press',      region: 'DE',     lang: 'DE',    url: 'https://www.pcgames.de/', desc: 'German PC & console coverage.' },
  { id: 'jeuxvideo',      name: 'Jeuxvideo.com',              type: 'Press',      region: 'FR',     lang: 'FR',    url: 'https://www.jeuxvideo.com/', desc: 'French-language coverage.' },
  { id: 'famitsu',        name: 'Famitsu',                    type: 'Press',      region: 'JP',     lang: 'JP',    url: 'https://www.famitsu.com/', desc: 'Japanese gaming press.' },
  { id: 'vandal',         name: 'Vandal.net',                 type: 'Press',      region: 'ES',     lang: 'ES',    url: 'https://vandal.elespanol.com/', desc: 'Spanish-language gaming coverage.' },
  { id: 'multiplayer',    name: 'Multiplayer.it',             type: 'Press',      region: 'IT',     lang: 'IT',    url: 'https://www.multiplayer.it/', desc: 'Italian gaming news and reviews.' },
  { id: 'gamevicio',      name: 'GameVício',                  type: 'Press',      region: 'BR',     lang: 'PT',    url: 'https://www.gamevicio.com/', desc: 'Brazilian Portuguese gaming coverage.' },
  { id: 'wiki',           name: 'GTA Fandom Wiki',            type: 'Reference',  region: 'Global', lang: 'Multi', url: 'https://gta.fandom.com/wiki/Grand_Theft_Auto_VI', desc: 'Community encyclopedia.' },
  { id: 'leaks',          name: 'Leak Watch (community)',     type: 'Leaks',      region: 'Global', lang: 'EN',    url: 'https://www.reddit.com/r/GTA6/', desc: 'Unverified rumors — treat with caution.' },
];

const DAY = 86400000;
// Relative dates are derived from a fixed "now" so the demo stays stable.
const NOW = new Date('2026-06-27T12:00:00Z').getTime();
const ago = (d) => new Date(NOW - d * DAY).toISOString();

export const ARTICLES = [
  {
    id: 'a1',
    title: 'GTA 6 confirmed for November 19, 2026 — Rockstar locks the date',
    excerpt: 'Rockstar Games confirms the worldwide release date for Grand Theft Auto VI on PS5 and Xbox Series X|S.',
    body: `Rockstar Games has officially confirmed that Grand Theft Auto VI will launch on November 19, 2026 for PlayStation 5 and Xbox Series X|S. The announcement ends months of speculation about a possible delay.\n\nThe studio reiterated that the game is set in the state of Leonida and its sprawling city of Vice City, returning the series to a modern-day Florida-inspired setting. A PC version was not dated at this time, consistent with Rockstar's past staggered rollouts.\n\nPre-orders are expected to open closer to launch. Rockstar thanked fans for their patience and promised additional media "in the months ahead."`,
    category: 'Official',
    source: 'rockstar', sourceUrl: 'https://www.rockstargames.com/VI',
    region: 'Global', lang: 'EN',
    author: 'Newswire',
    date: ago(2),
    image: 'gradient-1',
    verified: true,
    likes: 4821,
    featured: true,
  },
  {
    id: 'a2',
    title: 'Trailer 2 breaks views record in first 24 hours',
    excerpt: 'The second official trailer racked up record-breaking numbers across YouTube within a single day.',
    body: `The second official trailer for GTA 6 has shattered first-day view records, amassing tens of millions of views within 24 hours of release. Fans dissected every frame for clues about the map, the dual protagonists Lucia and Jason, and returning series staples.\n\nAnalysts noted the trailer's heavy emphasis on a living, reactive world — dynamic NPC routines, weather, and a notably denser Vice City skyline.`,
    category: 'Trailer',
    source: 'youtube', sourceUrl: 'https://www.youtube.com/@RockstarGames',
    region: 'Global', lang: 'EN',
    author: 'Media Desk',
    date: ago(5),
    image: 'gradient-2',
    verified: true,
    likes: 9210,
    featured: false,
  },
  {
    id: 'a3',
    title: 'Map size reportedly the largest in series history',
    excerpt: 'Community analysis of trailer footage suggests Leonida dwarfs previous GTA maps.',
    body: `Community cartographers piecing together trailer footage believe the state of Leonida will be the largest open world Rockstar has ever shipped, combining a dense Vice City with extensive rural wetlands, beaches and the Keys-inspired island chain.\n\nNothing here is official — treat reconstructed maps as fan estimates until Rockstar confirms dimensions.`,
    category: 'Map',
    source: 'reddit', sourceUrl: 'https://www.reddit.com/r/GTA6/',
    region: 'Global', lang: 'EN',
    author: 'r/GTA6',
    date: ago(8),
    image: 'gradient-3',
    verified: false,
    likes: 3344,
    featured: false,
  },
  {
    id: 'a4',
    title: 'Who are Lucia and Jason? A look at GTA 6\'s dual protagonists',
    excerpt: 'For the first time, a mainline GTA features a playable female lead alongside her partner.',
    body: `GTA 6 marks a series first with Lucia, a playable female protagonist, partnered with Jason in a Bonnie-and-Clyde-style story. Rockstar has shown the pair navigating heists and a relationship under pressure.\n\nExpect a narrative built around switching between the two, echoing the multi-protagonist structure pioneered in GTA V but tightened around a central duo.`,
    category: 'Characters',
    source: 'ign', sourceUrl: 'https://www.ign.com/games/grand-theft-auto-6',
    region: 'US', lang: 'EN',
    author: 'IGN Staff',
    date: ago(11),
    image: 'gradient-4',
    verified: true,
    likes: 5102,
    featured: false,
  },
  {
    id: 'a5',
    title: 'PC version: what we know (and don\'t)',
    excerpt: 'No PC date yet — here is how Rockstar has handled PC launches historically.',
    body: `As with GTA V and RDR2, GTA 6 launches first on current-gen consoles, with PC traditionally following months later. Rockstar has not announced a PC date.\n\nIf history repeats, PC players may wait the better part of a year — though Rockstar has faced growing pressure to shorten that gap.`,
    category: 'Official',
    source: 'gamespot', sourceUrl: 'https://www.gamespot.com/games/grand-theft-auto-6/',
    region: 'US', lang: 'EN',
    author: 'GameSpot',
    date: ago(14),
    image: 'gradient-5',
    verified: true,
    likes: 2210,
    featured: false,
  },
  {
    id: 'a6',
    title: 'Leak roundup: separating signal from noise',
    excerpt: 'A measured look at the week\'s rumors and why most should be taken with caution.',
    body: `Another week, another wave of GTA 6 "leaks." We compiled the most-discussed claims and rated their plausibility. As always: unverified community leaks are not confirmation. Rockstar rarely comments on rumors.\n\nOur credibility meter below lets the community vote on how believable each rumor is.`,
    category: 'Leak',
    source: 'leaks', sourceUrl: 'https://www.reddit.com/r/GTA6/',
    region: 'Global', lang: 'EN',
    author: 'Leak Watch',
    date: ago(17),
    image: 'gradient-6',
    verified: false,
    likes: 1880,
    featured: false,
  },
  {
    id: 'a7',
    title: 'GTA 6 in Deutschland: Was Fans hier wissen müssen',
    excerpt: 'Deutschsprachige Zusammenfassung der wichtigsten offiziellen Ankündigungen.',
    body: `Die deutschsprachige Community fiebert dem Release am 19. November 2026 entgegen. GameStar und andere Magazine fassen die offiziellen Ankündigungen zusammen: Schauplatz ist der Bundesstaat Leonida mit Vice City.\n\nEine USK-Einstufung steht noch aus, wird aber wie bei früheren Teilen erwartet.`,
    category: 'Official',
    source: 'gamestar', sourceUrl: 'https://www.gamestar.de/',
    region: 'DE', lang: 'DE',
    author: 'GameStar',
    date: ago(20),
    image: 'gradient-7',
    verified: true,
    likes: 1290,
    featured: false,
  },
  {
    id: 'a8',
    title: 'Vice City returns: a modern take on the 1986 classic',
    excerpt: 'How Rockstar is reimagining its most iconic city for current-gen hardware.',
    body: `Vice City, last visited in the 1980s-set classic, returns in a contemporary form. Trailer footage shows neon-soaked nightlife, beachfront high-rises and a denser, more reactive crowd than any prior GTA.\n\nThe city is the beating heart of the new state of Leonida.`,
    category: 'Map',
    source: 'eurogamer', sourceUrl: 'https://www.eurogamer.net/',
    region: 'EU', lang: 'EN',
    author: 'Eurogamer',
    date: ago(24),
    image: 'gradient-8',
    verified: true,
    likes: 2670,
    featured: false,
  },
  {
    id: 'a9',
    title: 'Pre-order details expected later this year',
    excerpt: 'Rockstar signals pre-orders and editions will be announced closer to launch.',
    body: `Rockstar has indicated that pre-order details, special editions and platform-specific bonuses will arrive closer to the November 2026 launch. No pricing has been confirmed.\n\nWe'll update this section the moment official storefront listings go live.`,
    category: 'Official',
    source: 'rockstar', sourceUrl: 'https://www.rockstargames.com/VI',
    region: 'Global', lang: 'EN',
    author: 'Newswire',
    date: ago(28),
    image: 'gradient-9',
    verified: true,
    likes: 1450,
    featured: false,
  },
  {
    id: 'a10',
    title: 'Soundtrack speculation: which radio stations could return?',
    excerpt: 'Fans hope for a sprawling licensed soundtrack worthy of a modern Vice City.',
    body: `GTA radio is a series institution. With a 1980s-rooted Vice City reborn in the present day, fans are speculating about genre-spanning stations blending synthwave nostalgia with contemporary Latin, hip-hop and pop.\n\nNothing is confirmed — but Rockstar's music licensing has historically been a highlight.`,
    category: 'Trailer',
    source: 'reddit', sourceUrl: 'https://www.reddit.com/r/GTA6/',
    region: 'Global', lang: 'EN',
    author: 'r/GTA6',
    date: ago(33),
    image: 'gradient-10',
    verified: false,
    likes: 990,
    featured: false,
  },
  {
    id: 'a11',
    title: 'Famitsu: 日本でのGTA 6への期待',
    excerpt: 'ファミ通が2026年11月19日発売予定のグランド・セフト・オートVIへの期待感を特集。',
    body: `ファミ通は、2026年11月19日に全世界同時発売予定の『グランド・セフト・オートVI』への期待感を特集した。デュアル主人公システムや、レオニダ州の広大なオープンワールドが国内ファンの間でも大きな注目を集めている。\n\n日本市場向けの日本語吹き替えおよび字幕の有無については、まだ公式発表がなく、ファンコミュニティで議論が続いている。過去作（GTA V）と同様の完全日本語対応が期待されているが、詳細はロックスター・ゲームスからの続報を待つ必要がある。`,
    category: 'Official',
    source: 'famitsu', sourceUrl: 'https://www.famitsu.com/',
    region: 'JP', lang: 'JP',
    author: 'Famitsu',
    date: ago(38),
    image: 'gradient-11',
    verified: true,
    likes: 760,
    featured: false,
  },
  {
    id: 'a13',
    title: 'GTA 6 : ce que la communauté française attend du retour à Vice City',
    excerpt: 'Jeuxvideo.com fait le point sur les attentes des joueurs francophones avant la sortie mondiale du 19 novembre 2026.',
    body: `La communauté francophone trépigne d'impatience à l'approche de la sortie de Grand Theft Auto VI, prévue le 19 novembre 2026 sur PS5 et Xbox Series X|S. Le retour à Vice City, modernisé pour le hardware actuel, suscite un vif enthousiasme — notamment grâce aux images spectaculaires du second trailer.\n\nLes joueurs francophones espèrent une localisation complète, avec doublage et sous-titres en français, dans la continuité de GTA V. Aucune annonce officielle n'a encore été faite à ce sujet. Rockstar Games devrait communiquer davantage sur les versions localisées dans les semaines précédant le lancement.`,
    category: 'Official',
    source: 'jeuxvideo', sourceUrl: 'https://www.jeuxvideo.com/',
    region: 'EU', lang: 'FR',
    author: 'Jeuxvideo.com',
    date: ago(22),
    image: 'gradient-13',
    verified: true,
    likes: 870,
    featured: false,
  },
  {
    id: 'a12',
    title: 'Online mode: what could the future of GTA Online look like?',
    excerpt: 'With GTA V\'s online juggernaut, all eyes are on GTA 6\'s multiplayer plans.',
    body: `GTA Online generated enormous revenue across a decade. Rockstar has not detailed GTA 6's online component, but expectations are high for a next-generation evolution rather than a simple sequel.\n\nExpect more details after the single-player launch, mirroring GTA V's rollout.`,
    category: 'Official',
    source: 'ign', sourceUrl: 'https://www.ign.com/games/grand-theft-auto-6',
    region: 'US', lang: 'EN',
    author: 'IGN Staff',
    date: ago(45),
    image: 'gradient-12',
    verified: false,
    likes: 1670,
    featured: false,
  },
];

export const TIMELINE = [
  { date: '2018-01-01', title: 'Early development reported', desc: 'Industry sources indicate Rockstar began early-stage GTA 6 development following Red Dead Redemption 2.' },
  { date: '2022-02-04', title: 'Rockstar confirms development', desc: 'Rockstar officially confirms the next Grand Theft Auto is in active development — ending years of speculation.' },
  { date: '2022-09-18', title: 'Massive source-code leak', desc: '90+ early gameplay clips and internal source code surface — the largest gaming leak at the time. Rockstar confirms authenticity and promises to continue development.' },
  { date: '2023-12-04', title: 'Trailer 1 — record 90 M views', desc: 'Trailer 1 debuts and hits 90 million YouTube views in 24 hours, a record at the time. Confirms Vice City, the state of Leonida and protagonist Lucia.' },
  { date: '2024-04-06', title: 'Take-Two narrows launch window', desc: 'Take-Two Interactive earnings call mentions fiscal year 2025 window, sparking speculation about a possible delay.' },
  { date: '2025-04-25', title: 'Delay to autumn 2026 confirmed', desc: 'Rockstar announces the game is delayed from an earlier window to autumn 2026 to ensure the highest quality release.' },
  { date: '2026-03-06', title: 'Release date locked: Nov 19', desc: 'Rockstar confirms November 19, 2026 as the worldwide release date for PlayStation 5 and Xbox Series X|S.' },
  { date: '2026-06-22', title: 'Trailer 2 breaks records again', desc: 'A second trailer breaks Trailer 1\'s first-day view record, revealing Jason as second protagonist and showing dynamic NPC systems.' },
  { date: '2026-09-01', title: 'Pre-order details announced', desc: 'Official pre-order details, editions and digital bonuses go live across all major storefronts.' },
  { date: '2026-10-15', title: 'Final content showcase', desc: 'A dedicated State of Play / Rockstar showcase reveals gameplay, online details and launch day roadmap.' },
  { date: '2026-11-19', title: 'Worldwide release', desc: 'GTA 6 launches simultaneously worldwide on PS5 and Xbox Series X|S. The wait is over.' },
];

export const FAQ = [
  { q: 'When does GTA 6 release?', a: 'November 19, 2026, simultaneously worldwide on PlayStation 5 and Xbox Series X|S.' },
  { q: 'Is there a PC version?', a: 'No PC date has been announced. Rockstar has historically released PC versions months after console launch (GTA V: ~18 months, RDR2: ~14 months).' },
  { q: 'Which platforms are confirmed?', a: 'PlayStation 5 and Xbox Series X|S on launch day. No current-gen (PS4/Xbox One) or PC release has been confirmed.' },
  { q: 'Where is GTA 6 set?', a: 'In the state of Leonida, centered on a modern reimagining of Vice City — the largest open world Rockstar has built to date.' },
  { q: 'Who are the protagonists?', a: 'Lucia (the series\' first playable female lead) and Jason, her partner in a Bonnie-and-Clyde-style story. You switch between the two.' },
  { q: 'Will there be a multiplayer / GTA Online successor?', a: 'Rockstar has not detailed the online component. Expect more information after the single-player launch, mirroring GTA V\'s rollout.' },
  { q: 'How much will GTA 6 cost?', a: 'No official pricing announced. Next-gen blockbusters typically launch at $69.99–$79.99 USD; special editions are expected.' },
  { q: 'How do I tell verified news from rumors?', a: 'Look for the green "✓ Verified" badge on articles and cards. Items marked "⚠ Rumor" come from unofficial channels and should be treated with caution.' },
  { q: 'Are leaks reliable?', a: 'Treat all leaks with caution — only Rockstar announcements are confirmation. The 2022 source-code leak was real, but many subsequent "leaks" were fabricated.' },
  { q: 'Where can I find official updates?', a: 'The Rockstar Newswire (rockstargames.com) and Rockstar\'s official YouTube, X and Instagram are the only authoritative sources.' },
];

export const POLLS = [
  { id: 'p1', q: 'Which feature are you most excited about?', options: ['Dual protagonists', 'Bigger map', 'Improved GTA Online', 'Modern Vice City'] },
  { id: 'p2', q: 'Will the PC version arrive within 6 months of launch?', options: ['Yes', 'No', 'No idea'] },
  { id: 'p3', q: 'How are you planning to play GTA 6 at launch?', options: ['Day-one purchase', 'Wait for a sale', 'Wait for PC', 'Still undecided'] },
];

export const CHARACTERS = [
  { name: 'Lucia', role: 'Protagonist', desc: 'The series\' first playable female lead.', image: 'gradient-2' },
  { name: 'Jason', role: 'Protagonist', desc: 'Lucia\'s partner in a Bonnie-and-Clyde story.', image: 'gradient-4' },
  { name: 'Vice City', role: 'Setting', desc: 'A modern reimagining of the iconic city.', image: 'gradient-8' },
  { name: 'Leonida', role: 'State', desc: 'The largest open world in series history (reported).', image: 'gradient-3' },
];

export function getArticles() {
  return ARTICLES.slice();
}
