apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gta6-news-hub
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  tls:
    - hosts:
        - gta6newshub.de
      secretName: gta6-tls
  rules:
    - host: gta6newshub.de
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gta6-news-hub
                port:
                  number: 80
